"""Canonical grouped browser contract shared by backend and sidecar."""

from windie_shared.browser_contract_catalog import (
    BROWSER_ACTION_CONTRACTS,
    BrowserActionContract,
)
from windie_shared.browser_contract_models import (
    BROWSER_CANONICAL_ACTIONS,
    MAX_BROWSER_TEXT_CHARS,
    BrowserActionArgsBase,
    BrowserCanonicalAction,
    BrowserClickArgs,
    BrowserCloseArgs,
    BrowserCloseTabArgs,
    BrowserConnectArgs,
    BrowserControlArgs,
    BrowserDoneArgs,
    BrowserEvaluateArgs,
    BrowserExtractArgs,
    BrowserFindElementsArgs,
    BrowserFindTextArgs,
    BrowserGetAttributesArgs,
    BrowserGetBboxArgs,
    BrowserGetTabsArgs,
    BrowserGetTextArgs,
    BrowserGetValueArgs,
    BrowserGoBackArgs,
    BrowserHoverArgs,
    BrowserInputArgs,
    BrowserMouseButton,
    BrowserNavigateArgs,
    BrowserProfilesArgs,
    BrowserReadFileArgs,
    BrowserReadLongContentArgs,
    BrowserReplaceFileArgs,
    BrowserSaveAsPdfArgs,
    BrowserScreenshotArgs,
    BrowserScrollArgs,
    BrowserScrollDirection,
    BrowserSearchArgs,
    BrowserSearchPageArgs,
    BrowserSelectDropdownArgs,
    BrowserSendKeysArgs,
    BrowserSnapshotArgs,
    BrowserStatusArgs,
    BrowserSwitchArgs,
    BrowserUploadFileArgs,
    BrowserWaitArgs,
    BrowserWriteFileArgs,
)
from windie_shared.browser_contract_schema import build_browser_tool_parameters_schema
