"""Sidecar browser schemas mirrored directly from the backend contract."""

from __future__ import annotations

from tools.browser.browser_action_contract import _ensure_repo_root_on_path

_ensure_repo_root_on_path()

from backend.src.tools.browser.schemas import (  # noqa: E402
    BROWSER_ACTION_CONTRACTS,
    BROWSER_ACTION_CONTRACTS_BY_NAME,
    BROWSER_ACTIONS_REQUIRING_CONNECTION,
    BROWSER_MODEL_VISIBLE_ACTIONS,
    BROWSER_RUNTIME_ACTIONS,
    BROWSER_SCHEMAS,
    BrowserActionContract,
    BrowserClickArgs,
    BrowserCloseArgs,
    BrowserCloseTabArgs,
    BrowserConnectArgs,
    BrowserControlArgs,
    BrowserDoneArgs,
    BrowserDropdownOptionsArgs,
    BrowserEvaluateArgs,
    BrowserExtractArgs,
    BrowserFindElementsArgs,
    BrowserFindTextArgs,
    BrowserGetTabsArgs,
    BrowserGoBackArgs,
    BrowserInputArgs,
    BrowserNavigateArgs,
    BrowserProfilesArgs,
    BrowserReadFileArgs,
    BrowserReadLongContentArgs,
    BrowserReplaceFileArgs,
    BrowserScreenshotArgs,
    BrowserScrollArgs,
    BrowserSearchArgs,
    BrowserSearchPageArgs,
    BrowserSelectDropdownArgs,
    BrowserSendKeysArgs,
    BrowserSnapshotArgs,
    BrowserStatusArgs,
    BrowserSwitchArgs,
    BrowserUploadFileArgs,
    BrowserWaitArgs,
    BrowserWriteFileArgs,
    build_browser_tool_parameters_schema,
    get_browser_schema,
    validate_browser_args,
)

__all__ = [
    "BROWSER_ACTION_CONTRACTS",
    "BROWSER_ACTION_CONTRACTS_BY_NAME",
    "BROWSER_ACTIONS_REQUIRING_CONNECTION",
    "BROWSER_MODEL_VISIBLE_ACTIONS",
    "BROWSER_RUNTIME_ACTIONS",
    "BROWSER_SCHEMAS",
    "BrowserActionContract",
    "BrowserClickArgs",
    "BrowserCloseArgs",
    "BrowserCloseTabArgs",
    "BrowserConnectArgs",
    "BrowserControlArgs",
    "BrowserDoneArgs",
    "BrowserDropdownOptionsArgs",
    "BrowserEvaluateArgs",
    "BrowserExtractArgs",
    "BrowserFindElementsArgs",
    "BrowserFindTextArgs",
    "BrowserGetTabsArgs",
    "BrowserGoBackArgs",
    "BrowserInputArgs",
    "BrowserNavigateArgs",
    "BrowserProfilesArgs",
    "BrowserReadFileArgs",
    "BrowserReadLongContentArgs",
    "BrowserReplaceFileArgs",
    "BrowserScreenshotArgs",
    "BrowserScrollArgs",
    "BrowserSearchArgs",
    "BrowserSearchPageArgs",
    "BrowserSelectDropdownArgs",
    "BrowserSendKeysArgs",
    "BrowserSnapshotArgs",
    "BrowserStatusArgs",
    "BrowserSwitchArgs",
    "BrowserUploadFileArgs",
    "BrowserWaitArgs",
    "BrowserWriteFileArgs",
    "build_browser_tool_parameters_schema",
    "get_browser_schema",
    "validate_browser_args",
]
