/**
 * Exposes the package entrypoint for the renderer UI.
 */

export {
  createWindieLocalRuntimeProvider,
  moduleTool,
  SidecarDaemonHttpClient,
  WindieAgent,
  WindieClient,
  WindieAgentSession,
  WindieSdkClient,
} from './windieSdkClient';
export type {
  SdkArtifactUploadResponse,
  SdkBoundingBox,
  SdkConfigSnapshot,
  SdkImageMetadata,
  SdkImageSource,
  SdkModelsResponse,
  SdkOcrCandidateRequest,
  SdkOcrFindTextResponse,
  SdkOcrInspectRequest,
  SdkOcrInspectResponse,
  SdkOcrOverlayRequest,
  SdkOcrResolveCandidateResponse,
  SdkOcrResolveTextResponse,
  SdkOcrResult,
  SdkOcrRunRequest,
  SdkOcrRunResponse,
  SdkOcrTextQueryRequest,
  SdkOverlayArtifactResponse,
  SdkPoint,
  SdkPromptPreviewRequest,
  SdkPromptPreviewResponse,
  SdkQueryPlanRequest,
  SdkQueryPlanResponse,
  SdkSystemPromptResponse,
  SdkToolCapabilitiesResponse,
  SdkToolSchemasResponse,
  SdkVisionDescribeRequest,
  SdkVisionDescribeResponse,
  SdkVisionLocateAllRequest,
  SdkVisionLocateAllResponse,
  SdkVisionLocateRequest,
  SdkVisionLocateResponse,
  SdkVisionOverlayRequest,
  SdkVisionTarget,
  ToolSchema,
  WindieAutoSidecarOptions,
  SidecarDaemonClientOptions,
  WindieClientOptions,
  WindieAgentQueryInput,
  WindieLocalRuntimeClient,
  WindieLocalRuntimeProvider,
  WindieLocalRuntimeProviderContext,
  WindieMcpDefinition,
  WindiePluginDefinition,
  WindieSkillDefinition,
  WindieSdkClientOptions,
  WindieSdkQueryOptions,
  WindieToolDefinition,
  WindieWakeUpOptions,
} from './windieSdkClient';
