/**
 * Provides desktop-runtime IPC channel groups for the Electron main process.
 */

const IPC_CHANNELS = require('../../shared/ipcChannels.json');

const DESKTOP_RUNTIME_SEND_CHANNELS = Object.freeze({
  PENDING_TURN: IPC_CHANNELS.SEND_CHANNELS.DESKTOP_RUNTIME_PENDING_TURN,
});

const DESKTOP_RUNTIME_INVOKE_CHANNELS = Object.freeze({
  INVOKE: IPC_CHANNELS.INVOKE_CHANNELS.DESKTOP_RUNTIME_INVOKE,
  GET_LOCAL_RUNTIME_STATUS: IPC_CHANNELS.INVOKE_CHANNELS.GET_LOCAL_RUNTIME_STATUS,
});

const DESKTOP_RUNTIME_ON_CHANNELS = Object.freeze({
  ROWS: IPC_CHANNELS.ON_CHANNELS.DESKTOP_RUNTIME_ROWS,
  STATUS: IPC_CHANNELS.ON_CHANNELS.DESKTOP_RUNTIME_STATUS,
  CONVERSATION_EVENT: IPC_CHANNELS.ON_CHANNELS.DESKTOP_RUNTIME_CONVERSATION_EVENT,
  MEMORY_STORE_CHANGED: IPC_CHANNELS.ON_CHANNELS.DESKTOP_RUNTIME_MEMORY_STORE_CHANGED,
  CONVERSATION_METADATA_INVALIDATED:
    IPC_CHANNELS.ON_CHANNELS.DESKTOP_RUNTIME_CONVERSATION_METADATA_INVALIDATED,
  CURRENT_TURN: IPC_CHANNELS.ON_CHANNELS.DESKTOP_RUNTIME_CURRENT_TURN,
  PENDING_TURN: IPC_CHANNELS.ON_CHANNELS.DESKTOP_RUNTIME_PENDING_TURN,
  LOCAL_RUNTIME_STATUS: IPC_CHANNELS.ON_CHANNELS.LOCAL_RUNTIME_STATUS,
});

module.exports = {
  DESKTOP_RUNTIME_SEND_CHANNELS,
  DESKTOP_RUNTIME_INVOKE_CHANNELS,
  DESKTOP_RUNTIME_ON_CHANNELS,
};
