/**
 * Provides generic desktop-agent IPC channel aliases for the Electron main process.
 */

const IPC_CHANNELS = require('../../shared/ipcChannels.json');

const DESKTOP_AGENT_SEND_CHANNELS = Object.freeze({
  PENDING_TURN: IPC_CHANNELS.SEND_CHANNELS.WINDIE_PENDING_TURN,
});

const DESKTOP_AGENT_INVOKE_CHANNELS = Object.freeze({
  INVOKE: IPC_CHANNELS.INVOKE_CHANNELS.DESKTOP_AGENT_INVOKE,
});

const DESKTOP_AGENT_ON_CHANNELS = Object.freeze({
  ROWS: IPC_CHANNELS.ON_CHANNELS.WINDIE_ROWS,
  STATUS: IPC_CHANNELS.ON_CHANNELS.WINDIE_STATUS,
  CONVERSATION_EVENT: IPC_CHANNELS.ON_CHANNELS.WINDIE_CONVERSATION_EVENT,
  MEMORY_STORE_CHANGED: IPC_CHANNELS.ON_CHANNELS.WINDIE_MEMORY_STORE_CHANGED,
  CONVERSATION_METADATA_INVALIDATED:
    IPC_CHANNELS.ON_CHANNELS.WINDIE_CONVERSATION_METADATA_INVALIDATED,
  CURRENT_TURN: IPC_CHANNELS.ON_CHANNELS.WINDIE_CURRENT_TURN,
  PENDING_TURN: IPC_CHANNELS.ON_CHANNELS.WINDIE_PENDING_TURN,
});

module.exports = {
  DESKTOP_AGENT_SEND_CHANNELS,
  DESKTOP_AGENT_INVOKE_CHANNELS,
  DESKTOP_AGENT_ON_CHANNELS,
};
